version: "2"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      # simplify code: gofmt with `-s` option, true by default
      simplify: true
    goimports:
      # put imports beginning with prefix after 3rd-party packages;
      # it's a comma-separated list of prefixes
      local-prefixes:
        - github.com/elastic/go-freelru

linters:
  default: all
  disable:
    # Disabled because of
    #   - too many non-sensical warnings
    #   - not relevant for us
    #   - false positives
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - interfacebloat
    - ireturn
    - nlreturn
    - mnd
    - nolintlint
    - nonamedreturns
    - paralleltest
    - testpackage
    - thelper
    - varnamelen
    - wsl
    # disabled because Go 1.18
    - copyloopvar
    - intrange

  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enable-all: true
    gocyclo:
      min-complexity: 15
    gosec:
      excludes: 
        - G115
    govet:
      enable-all: true
      disable:
        - fieldalignment
      settings:
        printf: # analyzer name, run `go tool vet help` to see all analyzers
          funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
            - debug,debugf,debugln
            - error,errorf,errorln
            - fatal,fatalf,fataln
            - info,infof,infoln
            - log,logf,logln
            - warn,warnf,warnln
            - print,printf,println,sprint,sprintf,sprintln,fprint,fprintf,fprintln
    lll:
      line-length: 120
      tab-width: 4
    misspell:
      locale: US
