service:
  golangci-lint-version: 1.48.x

issues:
  exclude-dirs:
    - artifacts
    - build-targets
    - design
    - docker-images
    - docs
    - etc
    - experiments
    - infrastructure
    - legal
    - libpf-rs
    - mocks
    - pf-code-indexing-service/cibackend/gomock_*
    - pf-debug-metadata-service/dmsbackend/gomock_*
    - pf-host-agent/support/ci-kernels
    - pf-storage-backend/storagebackend/gomock_*
    - scratch
    - systemtests/benchmarks/_outdata
    - target
    - virt-tests
    - vm-images

linters:
  enable-all: true
  disable:
    # Disabled because of
    #   - too many non-sensical warnings
    #   - not relevant for us
    #   - false positives
    # 
    # "might be worth fixing" means we should investigate/fix in the mid term
    - containedctx # might be worth fixing
    - contextcheck # might be worth fixing
    - cyclop
    - depguard
    - dupword
    - durationcheck # might be worth fixing
    - err113
    - errname # might be worth fixing
    - errorlint # might be worth fixing
    - exhaustive
    - exhaustruct
    - forcetypeassert # might be worth fixing
    - funlen
    - gci # might be worth fixing
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godot
    - godox # complains about TODO etc
    - gofumpt
    - goimports # might be worth fixing
    - gomnd
    - gomoddirectives
    - interfacebloat
    - ireturn
    - maintidx
    - makezero
    - mnd
    - nestif
    - nilerr # might be worth fixing
    - nilnil
    - nlreturn
    - noctx # might be worth fixing
    - nolintlint
    - nonamedreturns
    - paralleltest
    - sqlclosecheck # might be worth fixing
    - tagalign
    - tagliatelle
    - testableexamples # might be worth fixing
    - testpackage
    - tparallel # might be worth fixing
    - thelper
    - varnamelen
    - wastedassign
    - wsl
    - wrapcheck
    - forbidigo
    # the following linters are deprecated
    - execinquery
    # we don't want to change code to Go 1.22+ yet
    - intrange
    - copyloopvar

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - sloppyReassign
      - uncheckedInlineErr # Experimental rule with high false positive rate.

      # Broken with Go 1.18 feature (https://github.com/golangci/golangci-lint/issues/2649):
      - hugeParam
      - rangeValCopy
      - typeDefFirst
      - paramTypeCombine
  gocyclo:
    min-complexity: 15
  govet:
    enable-all: true
    disable:
      - fieldalignment
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - debug,debugf,debugln
          - error,errorf,errorln
          - fatal,fatalf,fataln
          - info,infof,infoln
          - log,logf,logln
          - warn,warnf,warnln
          - print,printf,println,sprint,sprintf,sprintln,fprint,fprintf,fprintln
  lll:
    line-length: 120
    tab-width: 4
  maligned:
    suggest-new: true
  misspell:
    locale: US
